---
title: "Banks loans"
author: "Bashayr Alghamdi"
date: "05/12/2020"
output:   
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed

---

```{r setup, include=TRUE}
library(flexdashboard) # dashboard
library(rio) # read xlsx file

library(tidyverse)
library(ggplot2)
library(plotly)
library(plyr)

library(DT)



```

Home
=======================================================================
Column {.tabset}
-----------------------------------------------------------------------

### Company 

#### SOCIAL DEVELOPMENT BANK 

    
Provide financial and non-financial services and targeted savings plans supported by   qualified human resources to contribute in social development, building partnerships with
multiple sectors, spreading financial awareness and promoting a culture of   self-employment among all segments of society.

Social Development Bank provides its Open Data to all visitors and audiences to the bank’s website in order to enhance the transparency principles and motivate the electronic collaboration. The Bank has shared the data with the [Open Data](https://www.data.gov.sa/Data/en/organization/social_development_bank) Platform which contains number of files with different data in different formats that make it easy to process and re-use.


### Data

```{r}
#read data file 
loans <- import("Data/social-development-bank-loans-for-2019.xlsx")
datatable(loans %>% 
  group_by(type) %>% 
  summarise(mean=mean(loan_amount),maximum=max(loan_amount),minimum=min(loan_amount)))

```



### analyze


```{r}
#chart1
```



```{r}
#loans %>% 
 # count(branch) %>% 
  #mutate(branch=fct_reorder(branch,n)) %>% 
  #ggplot(aes(branch,n)) +
  #geom_col()+
  #geom_text(aes(label = n),
   #         size = 3,
   #         hjust = 0,
    #        vjust = 0)+
  #coord_flip()+
  #labs(y = "count")
```


report 
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

### target

  
what is limit of amount_loan that customer need depend on their data

```{r}

plot(loans$loan_amount,ylab = "loan amount")
boxplot(loans$loan_amount,main="Boxplot",horizontal = TRUE)

summary(loans$loan_amount)
#Q1 = 42000
#Q3 = 60000
#IQR = 60000 - 42000
```

This is upper value of loan_amount after that is outliers
```{r}
upper <- 60000+(60000 - 42000)*1.5 
upper
```
This is lower value of loan_amount before that is outliers

```{r}
lower <- 42000-(60000 - 42000)*1.5 
lower
```
How many outliers:
```{r}
#there are 3392 outliers
out <- boxplot.stats(loans$loan_amount)$out
length(out)
```




